#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Example 6.4 SVM regression

Developed for Machine Learning for Mechanical Engineers at the University of
South Carolina

@author: austin_downey
"""

import IPython as IP
IP.get_ipython().run_line_magic('reset', '-sf')

import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk



plt.close('all')

#%% build the data sets
np.random.seed(2) # 2 and 6 are pretty good
m = 100
X = 6 * np.random.rand(m,1) - 3
y = 0.5 * X**2 + X + 2 + np.random.randn(m,1)
y = y.ravel()


#X = 6 * np.random.rand(m) - 3
#Y = 0.5 * X**2 + X + 2 + np.random.randn(m)

# plot the data
plt.figure()
plt.grid(True)
plt.scatter(X,y)
plt.xlabel('x')
plt.ylabel('y')


#%% SVM regression

svm_reg = sk.svm.SVR(kernel="poly", degree=3, C=1, epsilon=0.8, gamma="scale")
svm_reg.fit(X, y)

x1 = np.linspace(-3, 3, 100).reshape(100, 1)


# plot the data
plt.figure()
plt.grid(True)
plt.scatter(X,y,zorder=10)
plt.xlabel('x')
plt.ylabel('y')

# plot the SVR
y_pred = svm_reg.predict(x1)
plt.plot(x1, y_pred, "k-", linewidth=2, label=r"$\hat{y}$")
plt.plot(x1, y_pred + svm_reg.epsilon, "k--",label='curb')
plt.plot(x1, y_pred - svm_reg.epsilon, "k--")
plt.scatter(X[svm_reg.support_], y[svm_reg.support_], s=100, facecolors='#FFAAAA')

plt.legend(loc="upper left")
plt.title(r"$degree={}, C={}, \epsilon = {}$".format(svm_reg.degree, svm_reg.C, svm_reg.epsilon))

plt.tight_layout()


#%% Implement a grid search on the data


parameters = {'kernel':['poly','linear','rbf'], 'C':np.arange(1, 100, 2).tolist(),
              'degree':[1,2,3],'epsilon':np.arange(0.1, 1, 0.1).tolist()}
svr = sk.svm.SVR()
reg = sk.model_selection.GridSearchCV(svr, parameters)
reg.fit(X, y)


# plot the data
plt.figure()
plt.grid(True)
plt.scatter(X,y,zorder=10)
plt.xlabel('x')
plt.ylabel('y')

# plot the SVR
y_pred = reg.predict(x1)
plt.plot(x1, y_pred, "k-", linewidth=2, label=r"$\hat{y}$")
plt.plot(x1, y_pred + reg.best_params_['epsilon'], "k--",label='curb')
plt.plot(x1, y_pred - reg.best_params_['epsilon'], "k--")

plt.legend(loc="upper left")
plt.title(r"$degree={}, C={}, \epsilon = {}$".format(reg.best_params_['degree'],
                            reg.best_params_['C'], reg.best_params_['epsilon']))

# The svr object generated by the grid search does not have the ".support_" class 
# so I have to re-rune the model like this to get the markers.
reg_support = sk.svm.SVR(kernel="rbf", degree=reg.best_params_['degree'],
                    C=reg.best_params_['C'], epsilon=reg.best_params_['epsilon'])
reg_support.fit(X, y)
plt.scatter(X[reg_support.support_], y[reg_support.support_], s=100,
            facecolors='#FFAAAA')

plt.tight_layout()

























